config/routes.rb
Rails.application.routes.draw do
    mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	  resources :posts


 resources :comments do
  member do
    put "like", to: "commments#upvote"
    put "dislike", to: "comments#downvote"
  end
end

resources :posts do
	member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  resources :comments
end
  resources :tags, only: [:index, :show]

  devise_for :users
  get '/users/:id', to: 'users#show', as: 'profile'
  root to: "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
		belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	  include Bootsy::Container


	 is_impressionable
	 acts_as_votable
	   acts_as_taggable_on :tags

validate :bad_words,:bad_title

def bad_words
  profanity_filter = LanguageFilter::Filter.new matchlist: :profanity
  if profanity_filter.match? description then
    errors.add(:description, "The following language is inappropriate in a use: #{profanity_filter.matched(description).join(', ')}")
end
end

def bad_title
profanity_filter = LanguageFilter::Filter.new matchlist: :profanity
  if profanity_filter.match? title then
    errors.add(:title, "The following language is inappropriate in a use: #{profanity_filter.matched(description).join(', ')}")
end	
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
      @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
   @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id if current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment for the above post is given.' }
        # format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was updated for the above post.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to posts_path}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body,:user_id,:post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index , :show]
  impressionist :actions=>[:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @per_page = params[:per_page] || Post.per_page || 5
    @posts=Post.where("title LIKE ?","%#{params[:search]}%").paginate(:page => params[:page], :per_page => @per_page).order(created_at: :desc)
   
       # @per_page = params[:per_page] || Question.per_page || 5
    # @posts=Post.where("title LIKE ?","%#{params[:search]}%")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end


  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

 def upvote
    @post=Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end

  def downvote
    @post=Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to posts_path
  end
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

     

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description,:user_id,:tag_list)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def show
  	@user = User.find(params[:id])

  	@user_posts = @user.posts
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
  <span class="label  label-info"">

<%= link_to tag.name, tag_path(tag) %>   
</span>

app/views/comments/_comment.html.erb
    <%= div_for(comment) do %>
        <div style="height:auto;width: 1000px;box-shadow: 0 0 2px 0px grey;margin-top:20px ">
            <div style="height:70px;background-color:rgba(0,0,0,0.2);margin: 0;padding:0,width: 100%">
                <div style="padding-left: 30px;padding-top: 10px;
">
                    <%= comment.user.name%> on
                        <%= comment.created_at.strftime("%B %d %Y, %l:%M%P") %>
                </div>
            </div>
            <div style="padding-left: 30px;padding-top: 10px;">
                <%= comment.body%>
                </div>
                            <div style="padding-left: 780px;">

                    <% if comment.user == current_user %>
                        <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
                            <%= link_to 'Edit',edit_comment_path(comment), class: "btn btn-primary"%>
                            </div>
                                <% end %>
            </br>
            <%end%>
        

app/views/comments/_form.html.erb
<center>
<%= simple_form_for ([@post,@comment])do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :body,label: "Comment" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</center>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', posts_path,class:"btn btn-success" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Demo App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Posts', '#' %></li>
                <% if current_user %>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mediforum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
    <% if notice %><div class = "alert alert-info"><%= notice%></div><% end%>
    <% if alert %><div class = "alert alert-warning"><%= alert%></div><%end%>
<%= render  "layouts/header" %>
<%=yield %>
<%= render "layouts/footer" %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>

        <div class="container">
        <div class="col-md-8">
            <div class="form-inputs">
                <%=f.input :title,placeholder: "How do I?.."%>
            </div>
            <div class="form-inputs">
               <%= f.label :tag_list, "Tags (separated by commas)" %><br />
              <%= f.input :tag_list, value: f.object.tag_list.to_s ,placeholder: "Tag question?..",input_html:{data:{role:'tagsinput'}} %>
</div>
                <div class="form-inputs">
                    <%=f.input :description,placeholder: "A Thing I need" %>
                </div>
            <div class="actions">
                <%= f.button :submit, "Ask your Question", class: "btn btn-success"%>
            </div>
            </br>
            <%= link_to 'Back', posts_path,class: "btn btn-primary" %>
            </div>

        </div>

        <% end %>

app/views/posts/_post.html.erb
<h2><%= link_to post.title, post_path(post) %></h2>

app/views/posts/index.html.erb
<p id="notice">
    <%= notice %>
</p>
<h1>Let's Discuss </h1>
<% if @posts.blank? %>
    <h4>There are no posts containing the term <%= params[:search] %></h4>
    <% end %>

<div class="form-group">
        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search],class:"search" %>
                                <%end%>
        </div>
        <div style="margin-left:990px">
                    <%= link_to 'Ask Question', new_post_path,class:"btn btn-primary"%>
                    </div>
        <div class="col-md-5 col-md-6">
            Show
            <%= select_tag :per_page, options_for_select([10,20,50], params[:per_page].to_i),
       :onchange => "if(this.value){window.location='?per_page='+this.value;}"%> entries
        </div>
        <table class="col md 8 table table-hover" style="margin-top:20px">
            <thead class="thead-dark">
                <tr>
                <th style="width: 50.66%;height: 40px">Topics</th>
                    <th>Votes</th>
                    <th>Submitted by</th>
                    <th>Replies</th>
                    <th>Views</th>
                    <th>Activity</th>
                </tr>
            </thead>
            <tbody>
             <tr>
                <% @posts.each do |post| %>
                        <td>
                            <%= link_to post.title, post %>
                                </br>
                                    <%= render post.tags %>
                                                     </td> 

                        <td>
                            <div class="btn-group">
                                <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
                                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                    <%= post.get_upvotes.size %>
                                        <% end %>
                                            <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
                                                <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                                                <%= post.get_downvotes.size %>
                                                    <% end %>
                                                        </br>
                                                        </br>
                            </div>
                            </div>
                            </td>

                            <td>
                                <%=link_to post.user.name,profile_path(post.user)%>
                            </td>
                            <td>
                                <%= post.comments.count %>
                            </td>
                            <td>
                                <%= post.impressionist_count %>
                            </td>
                            <td>
                                <%= time_ago_in_words(post.created_at)%> ago </td>
                        </td>
                       </tr>
                            <%end%>
            </tbody>
            </table>
            <center>
            <%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
            </center>
                <style type="text/css">
                     
.thead-dark
{
    width:120px;  
    white-space: nowrap; 
    overflow: hidden;
}
</style>
                

app/views/posts/new.html.erb
<h1>Ask A Question</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
 <i class="fa fa-question-circle" aria-hidden="true"></i>
 <div class="a" style:"width:50%;">
 <%= @post.title %>
 </div>
</h1>
<p>
Asked on <b><%= @post.created_at.strftime("%B %d %Y, %l:%M%P") %></b> By <b><%= @post.user.name %></b> 
</p>
 <% if @post.user == current_user %>
                        <%= link_to 'Delete',@post, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
                            <%= link_to 'Edit',edit_post_path(@post), class: "btn btn-primary"%>
                            <%end%>
<p>
  <strong>Views:</strong>
  <%= @post.impressionist_count %>
  </p>
<p>
<%= @post.comments.count %> comments:
 </p>
</p>
                
                    <%= render :partial => @post.comments %>
                       <div class="col-md-8">
     </br>
<%= simple_form_for [@post, Comment.new]  do |f| %>
        <div class="field">
            <%= f.input :body,label:"Comment"%>
            <%= f.submit "Add Comment", class: "btn btn-success" %>
        </div>
        <br>
            <% end %>
<%= link_to 'Back', posts_path,class:"btn btn-success"%>
</div>


<style>
div.a {
    white-space: nowrap; 
    overflow: hidden;
    text-overflow: ellipsis;
    width:50%;
}
div.a:hover {
    overflow: visible;
}
</style>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">MediForum</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      <%if user_signed_in?%>
        <li class="active"><%= link_to "Profile", profile_path(current_user.id) %></li>
        <%end%>

        <li><a href="#">BLOG</a></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to current_user.name, edit_user_registration_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
       <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<style>
 .search {
            width: 100px;
            margin-left: 10px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-position: 5px 10px;
            background-repeat: no-repeat;
            padding: 0px 0px 8px 0px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

        input[type=text]:focus {
            width: 60%;
        }
</style>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
 <center>
   <div class="col-md-12">
<div style="height:auto;width: 450px;box-shadow: 0 0 2px 0px grey;margin-top:20px ">
<h1>Tagged Name:<%= @tag.name %></h1>
<div><h2>Related Questions : <%= render @posts %></h2></div>
 </div>
</div>
 <%= link_to 'Back', posts_path,class: "btn btn-success "%>

</center>

app/views/users/show.html.erb
<h3>Welcome !!!</h3>
<h4>The Question Asked by :<%= @user.name %>  </h4>

<% @user_posts.each do |post| %>
<table table table-hover " style="margin-top:20px">
<tr>
 <th style="width: 50.66%;height: 40px">Topics</th>
  <th style="width: 50.66%;height: 40px">Descriptions</th>

 </tr>
 <tr>
<td><%= link_to post.title, post_path(post) %></td>
<td><%= post.description%></td>
</tr>
</table>



	<% end %>
	<br>
	<br>

	<%= link_to 'Back', posts_path %>